### ISSUE TITLE
Intellij 12 

### ISSUE THREAD

**Issue by fatlazycat** [combinatorial/AppCodeDashSearch#1]
Trying to install this plugin from disk and give an error of 'failed to load plugin descriptor from dash.jar'

Incompatible with intellij 12 ?

**Comment by combinatorial** [comment]
It's possible, I have only tried with AppCode 1.4 (newer versions of AppCode have a major performance problem on my projects). I don't recall which version of Intellij this was built with. You could try rebuilding the jar with a current version.

**Comment by justin808** [comment]
I tried with 5.4.3.2 of RubyMine and it also fails to load.

**Comment by combinatorial** [comment]
I suggest you file the issue on Kapeli's fork of this repo. He is the author of Dash, I am not longer using AppCode so can't maintain this code, maybe he can help... https://github.com/Kapeli/AppCodeDashSearch

**Comment by gdelmas** [comment]
don't know if it did not work before. but i compiled it today with intellij 12 and it works.

**Comment by gdelmas** [comment]
try this one: https://github.com/gdelmas/IntelliJDashPlugin/releases/tag/2.0
