### ISSUE TITLE
Error Message Class not found in PHPStorm

### ISSUE THREAD

**Issue by veelen** [combinatorial/AppCodeDashSearch#2]
I get the following error after launching PHPStorm with plugin installed.

"class with name "com.paperetto.dash.DashLauncherAction" not found [Plugin: com.paperetto.dash]: class with name "com.paperetto.dash.DashLauncherAction" not found [Plugin: com.paperetto.dash]"

The plugin does work properly.
I'am on a Mac using PHPStorm 6.0.1
![schermafbeelding 2013-09-27 om 08 59 35](https://f.cloud.github.com/assets/1203945/1224209/7c0623ca-2742-11e3-89d0-c87ed141bc9b.png)

**Comment by combinatorial** [comment]
Thanks for letting me know about the issue but I know longer use AppCode (which is also based on IntelliJ) and so do not have the time to investigate. You may want to try filing an issue against this repo... https://github.com/Kapeli/AppCodeDashSearch as this is a fork made by the developer of Dash.

**Comment by Kapeli** [comment]
Unfortunately, there's no need to open an issue on my fork. I have no idea how these plugins work so I won't be able to do anything about it :(

**Comment by combinatorial** [comment]
Should anyone want to take a look then all I did was follow the tutorials... http://confluence.jetbrains.com/display/IDEADEV/Getting+Started+with+Plugin+Development

**Comment by gdelmas** [comment]
is the bug still present with this (https://github.com/gdelmas/IntelliJDashPlugin/releases/tag/2.0) version?

**Comment by veelen** [comment]
No, it is not.
