### ISSUE TITLE
make a propper github release

### ISSUE THREAD

**Issue by falkorichter** [combinatorial/AppCodeDashSearch#4]
please remove the jar from the repository and make a propper release, witch a downloadable jar :)

**Comment by combinatorial** [comment]
How do I do that?

On Monday, November 11, 2013, Falko Richter wrote:

> please remove the jar from the repository and make a propper release,
> witch a downloadable jar :)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/combinatorial/AppCodeDashSearch/issues/4
> .

## 

David Brittain
david@paperetto.com

**Comment by falkorichter** [comment]
Delete the jar in the source repo
Then tap on the release button in github https://github.com/combinatorial/AppCodeDashSearch/releases and upload the release jar as a release. Click "Draft a new Release"
![screen shot 2013-11-12 at 15 53 31](https://f.cloud.github.com/assets/50506/1522584/45880502-4baa-11e3-8747-db13f75e1287.png)

**Comment by combinatorial** [comment]
Done. Thanks for the tip
